/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.sigei.views;

import org.sigei.controller.CadastroController;
import org.sigei.exception.ValidationException;
import org.sigei.model.CPF;
import org.sigei.model.pessoa.Organizador;
import org.sigei.model.pessoa.Participante;
import org.sigei.model.pessoa.Pessoa;
import org.sigei.model.usuario.enums.ETipoUsuario;
import org.sigei.validacao.MessageProvider;
import javax.swing.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Map;

/**
 *
 * @author mstom
 */
public class CadastroUsuarioForm extends javax.swing.JFrame {
    private static CadastroUsuarioForm instancia;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroUsuarioForm.class.getName());
    private final Map<String, String> campos;

    /**
     * Creates new form CadastroUsuarioForm
     */
    private CadastroUsuarioForm() {
        initComponents();
        campos = Map.of(
                "Nome", lblNome.getText().replace(":", ""),
                "Sobrenome", lblSobrenome.getText().replace(":", ""),
                "Cpf", lblCpf.getText().replace(":", ""),
                "DataNasc", lblPnDataNasc.getText().replace(":", ""),
                "Login", lblLogin.getText().replace(":", ""),
                "Senha", lblSenha.getText().replace(":", "")
        );
        cmbBoxTipoUsuario.addActionListener(e -> atualizarCampos());
        atualizarCampos();

        pack();
    }

    private void atualizarCampos() {
        ETipoUsuario tipoSelecionado = (ETipoUsuario) cmbBoxTipoUsuario.getSelectedItem();

        boolean mostrarNascimento = tipoSelecionado == ETipoUsuario.PARTICIPANTE;
        pnlDataNasc.setVisible(mostrarNascimento);

        jPanel1.revalidate();
        jPanel1.repaint();
        pack();
    }

    public static CadastroUsuarioForm getInstance() {
        if (instancia == null) {
            instancia = new CadastroUsuarioForm();
        }

        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCadastro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        cmbBoxTipoUsuario = new javax.swing.JComboBox<>(ETipoUsuario.selecionaveis());
        lblTipoUsuario = new javax.swing.JLabel();
        mskTxtCpf = new javax.swing.JFormattedTextField();
        lblCredenciais = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        pnlDataNasc = new javax.swing.JPanel();
        lblPnDataNasc = new javax.swing.JLabel();
        lblDiaNasc = new javax.swing.JLabel();
        lblMesNasc = new javax.swing.JLabel();
        lblAnoNasc = new javax.swing.JLabel();
        txtDiaNasc = new javax.swing.JFormattedTextField();
        txtMesNasc = new javax.swing.JFormattedTextField();
        txtAnoNasc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(253, 216, 53));
        lblCadastro.setText("CADASTRE-SE AQUI");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(240, 240, 240));
        lblNome.setLabelFor(txtNome);
        lblNome.setText("Nome:");

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(240, 240, 240));
        lblCpf.setLabelFor(mskTxtCpf);
        lblCpf.setText("CPF:");
        lblCpf.setToolTipText("");

        txtNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(240, 240, 240));
        lblSobrenome.setLabelFor(txtSobrenome);
        lblSobrenome.setText("Sobrenome:");

        txtSobrenome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbBoxTipoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(240, 240, 240));
        lblTipoUsuario.setLabelFor(cmbBoxTipoUsuario);
        lblTipoUsuario.setText("Tipo de usuário:");

        mskTxtCpf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            mskTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCredenciais.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblCredenciais.setForeground(new java.awt.Color(240, 240, 240));
        lblCredenciais.setText("Credenciais");

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(240, 240, 240));
        lblLogin.setLabelFor(txtLogin);
        lblLogin.setText("Login:");
        lblLogin.setToolTipText("");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(240, 240, 240));
        lblSenha.setLabelFor(txtSenha);
        lblSenha.setText("Senha:");

        txtLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(194, 24, 91));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("CADASTRAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnlDataNasc.setBackground(new java.awt.Color(28, 28, 28));

        lblPnDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPnDataNasc.setForeground(new java.awt.Color(240, 240, 240));
        lblPnDataNasc.setText("Data de Nascimento");

        lblDiaNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiaNasc.setForeground(new java.awt.Color(240, 240, 240));
        lblDiaNasc.setLabelFor(lblDiaNasc);
        lblDiaNasc.setText("Dia");

        lblMesNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMesNasc.setForeground(new java.awt.Color(240, 240, 240));
        lblMesNasc.setLabelFor(txtMesNasc);
        lblMesNasc.setText("Mês");

        lblAnoNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnoNasc.setForeground(new java.awt.Color(240, 240, 240));
        lblAnoNasc.setLabelFor(txtAnoNasc);
        lblAnoNasc.setText("Ano");

        txtDiaNasc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtDiaNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtMesNasc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtMesNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMesNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesNascActionPerformed(evt);
            }
        });

        txtAnoNasc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtAnoNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlDataNascLayout = new javax.swing.GroupLayout(pnlDataNasc);
        pnlDataNasc.setLayout(pnlDataNascLayout);
        pnlDataNascLayout.setHorizontalGroup(
            pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNascLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(pnlDataNascLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblPnDataNasc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDataNascLayout.setVerticalGroup(
            pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNascLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPnDataNasc)
                .addGap(16, 16, 16)
                .addGroup(pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaNasc)
                    .addComponent(lblMesNasc)
                    .addComponent(lblAnoNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDataNascLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(txtSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSobrenome))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxTipoUsuario, 0, 219, Short.MAX_VALUE)
                            .addComponent(lblTipoUsuario)
                            .addComponent(mskTxtCpf)))
                    .addComponent(pnlDataNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCredenciais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadastro)
                        .addGap(156, 156, 156))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCadastro)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mskTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobrenome)
                    .addComponent(lblTipoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCredenciais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(lblLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cadastrarUsuario();
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!",
                    "Erro", JOptionPane.INFORMATION_MESSAGE);
        } catch (ValidationException e) {
            e.getMessages().forEach((chave, valor) -> {
                JOptionPane.showMessageDialog(this, MessageProvider.get(valor, campos.get(chave)),
                        "Erro", JOptionPane.ERROR_MESSAGE);
            });} catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMesNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesNascActionPerformed

    private void cadastrarUsuario() throws ValidationException, SQLException, ClassNotFoundException {
        ETipoUsuario tipoUsuario = (ETipoUsuario) cmbBoxTipoUsuario.getSelectedItem();
        Pessoa p;
            if (tipoUsuario == ETipoUsuario.PARTICIPANTE) {
                int diaNasc = Integer.parseInt(txtDiaNasc.getText());
                int mesNasc = Integer.parseInt(txtMesNasc.getText());
                int anoNasc = Integer.parseInt(txtAnoNasc.getText());
                p = new Participante(new CPF(mskTxtCpf.getText()),
                        txtNome.getText(), txtSobrenome.getText(),
                        LocalDate.of(anoNasc, mesNasc, diaNasc));
            } else {
                p = new Organizador(new CPF(mskTxtCpf.getText()),
                        txtNome.getText(), txtSobrenome.getText());
            }

            new CadastroController().cadastrar(p, txtLogin.getText(), new String(txtSenha.getPassword()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroUsuarioForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ETipoUsuario> cmbBoxTipoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnoNasc;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCredenciais;
    private javax.swing.JLabel lblDiaNasc;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMesNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPnDataNasc;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JFormattedTextField mskTxtCpf;
    private javax.swing.JPanel pnlDataNasc;
    private javax.swing.JFormattedTextField txtAnoNasc;
    private javax.swing.JFormattedTextField txtDiaNasc;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JFormattedTextField txtMesNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
